apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rabbitmq.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: rabbitmq-server
